// <auto-generated />
using System;
using ExaAtendimento.InfraData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExaAtendimento.InfraData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Assunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAssunto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.HasIndex("TipoAssunto")
                        .IsUnique()
                        .HasDatabaseName("ix_assunto_tipoAssunto");

                    b.ToTable("assuntos", (string)null);
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("AssuntoId")
                        .HasColumnType("int");

                    b.Property<int>("AtendimentoConcluido")
                        .HasColumnType("int");

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteCodigo")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("CobrarCliente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("DataAtendimento")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Encerrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan?>("HoraFinal")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicial")
                        .HasColumnType("time");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("NumTipoAtendimento")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SugestaoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAtendimentoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.HasIndex("CaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ModuloId");

                    b.HasIndex("SugestaoId");

                    b.HasIndex("TipoAtendimentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("atendimentos", (string)null);
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Ca", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_ca_nome");

                    b.ToTable("cas", (string)null);
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CaCompartilhadaId")
                        .HasColumnType("int");

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("CaCompartilhadaId");

                    b.HasIndex("CaId");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_cliente_nome");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_modulo_nome");

                    b.ToTable("modulos", (string)null);
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Sugestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_sugestao_descricao");

                    b.ToTable("sugestoes", (string)null);
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.TipoAtendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_tipoatendimento_descricao");

                    b.ToTable("tipoatendimentos", (string)null);
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OldSenha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResetSenhaExpiracao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ResetSenhaToken")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.HasIndex("ModuloId");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_nome");

                    b.HasIndex("ResetSenhaToken")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_token");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Assunto", b =>
                {
                    b.HasOne("ExaAtendimento.Domain.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assunto_modulo");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("ExaAtendimento.Domain.Entities.Assunto", "Assunto")
                        .WithMany()
                        .HasForeignKey("AssuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atendimento_assunto");

                    b.HasOne("ExaAtendimento.Domain.Entities.Ca", "Ca")
                        .WithMany()
                        .HasForeignKey("CaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atendimento_ca");

                    b.HasOne("ExaAtendimento.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_atendimento_cliente");

                    b.HasOne("ExaAtendimento.Domain.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atendimento_modulo");

                    b.HasOne("ExaAtendimento.Domain.Entities.Sugestao", "Sugestao")
                        .WithMany()
                        .HasForeignKey("SugestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atendimento_sugestao");

                    b.HasOne("ExaAtendimento.Domain.Entities.TipoAtendimento", "TipoAtendimento")
                        .WithMany()
                        .HasForeignKey("TipoAtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atendimento_tipoatendimento");

                    b.HasOne("ExaAtendimento.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_atendimento_usuario");

                    b.Navigation("Assunto");

                    b.Navigation("Ca");

                    b.Navigation("Cliente");

                    b.Navigation("Modulo");

                    b.Navigation("Sugestao");

                    b.Navigation("TipoAtendimento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("ExaAtendimento.Domain.Entities.Ca", "CaCompartilhada")
                        .WithMany()
                        .HasForeignKey("CaCompartilhadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cliente_cacompartilhada");

                    b.HasOne("ExaAtendimento.Domain.Entities.Ca", "Ca")
                        .WithMany()
                        .HasForeignKey("CaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_ca");

                    b.Navigation("Ca");

                    b.Navigation("CaCompartilhada");
                });

            modelBuilder.Entity("ExaAtendimento.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ExaAtendimento.Domain.Entities.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuario_modulo");

                    b.Navigation("Modulo");
                });
#pragma warning restore 612, 618
        }
    }
}
